# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    environment: docker
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: 初始化
        uses: actions/checkout@v2
      - name: 初始化node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 安装依赖
        run: yarn
      - name: docker login
        run: docker login ${{ secrets.DOCKER_REPO }} -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: 构建镜像
        run: docker build -f Dockerfile -t registry.cn-hangzhou.aliyuncs.com/chino/lasoleil:github-ci-${{github.sha}} .
      - name: 推送镜像
        run: docker push registry.cn-hangzhou.aliyuncs.com/chino/lasoleil:github-ci-${{github.sha}}
